name: Trash Pickup Hobby Website
on:
  push:
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'
  workflow_dispatch:
    paths:
      - 'src/**'

jobs:
  deploy:
    name: Deploys static web assets to github pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: github-pages
          folder: src
          target-folder: docs
          clean: false

  websiteAcceptanceTests:
    name: Executes acceptance tests on website
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [deploy]
    steps:
      - uses: actions/checkout@v2
        with:
        - name: Install dependencies
          uses: tj-actions/puppeteer@v3.2
          with:
            args: npm --prefix ./acceptance-tests install
        - name: Run acceptance tests against staging environment
          uses: tj-actions/puppeteer@v3.2
          with:
            args: npm --prefix ./acceptance-tests run test-stage
        - name: Run acceptance tests against production environment
          uses: tj-actions/puppeteer@v3.2
          with:
            args: npm --prefix ./acceptance-tests run test-production
