name: Trash Pickup Hobby Website
on:
  push:
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'
  workflow_dispatch:
    paths:
      - 'src/**'

jobs:
  deploy:
    name: Deploys static web assets to github pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: github-pages
          folder: src
          target-folder: docs
          clean: false

  websiteAcceptanceTests:
    name: Executes acceptance tests on website
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [deploy]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm --prefix ./acceptance-tests install
      - run: npm --prefix ./acceptance-tests run test-stage
      - run: npm --prefix ./acceptance-tests run test-production
